export const ActionTypes={
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    FETCH_PRODUCT_ID : "FETCH_PRODUCT_ID",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT"

}